name: Tasting RenoVATES

on:
  pull_request_target:

jobs:
  just-printing-stuff:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'renovate[bot]' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Show branch/ref
        run: |
          echo "PR HEAD REF = ${{ github.event.pull_request.head.ref }}"
          echo "PR HEAD SHA = ${{ github.event.pull_request.head.sha }}"
